### ISSUE TITLE
Bias

### ISSUE THREAD

**Issue by MrMagma** [Team-Delta-KA/KA-Contest-Judging-System#1]
I thought I should bring this up. Pamela's description of the possible app mentioned that it wouldn't include usernames so as to prevent bias. That's good, but someone brought up the fact that some users include their names/logos in the program ([Their post is here](https://www.khanacademy.org/computer-programming/app-idea-contest-voting-app/5448182776594432?qa_expand_key=kaencrypted_f25cf5244fa34e47e457431f0e2feda3_8b7cc22de346a21339fbd939324d06009f1de8910b10c8b53c5257b2337862d18edea78d26e978dac1a839e222d9d6cca270c600aed48513b4212435a7330f3ee74b0e72feb0b0a69f00a698ba68920351c8c5cacfcec3aa5a70bf941febed436b5f16bde1bb231a0b42c58a6b14dc1660266fd92b4c09dbba174751a0494ee71165669a9c79cf8831b0675f704c44ab8038f5b9d1974cdc3a63af5a6d95c7cb))
I thought I should add this as an issue here to make sure it's considered, if you want to close it you can.

**Comment by codeHusky** [comment]
The judges are planned to be hand-picked, so technically there shouldn't be any bias.

**Comment by bytorbrynden** [comment]
As @MikaalSky; judges will be hand picked.

We will be putting another system in place to remove usernames and/or anything else that could cause biased judging.

**Comment by codeHusky** [comment]
Also, we really can only do so much. I think hiding the editor until the code-related criteria are applicable would be wise.

**Comment by Noble-Mushtak** [comment]
@Gigabyte-Giant recently warned users of bias from seeing entries on KA in `Client/scripts/entry.js`: https://github.com/Team-Delta-KA/KA-Contest-Judging-System/blob/master/Client/scripts/entry.js#L222

**Comment by Noble-Mushtak** [comment]
@Gigabyte-Giant I think we should close this issue since it's basically been solved by [entry.js](https://github.com/Team-Delta-KA/KA-Contest-Judging-System/blob/master/Client/scripts/entry.js#L237) and it's taking up visual space among the GitHub Issues this repo has. If there's still more to be done on this, it should probably go in Trello under To-Do so we can do it later.
