### ISSUE TITLE
Entry previews do not load in Firefox

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#14]
Title says it all.

**Comment by bytorbrynden** [comment]
For whatever reason; `KAdefine` doesn't get defined in Firefox... That's ironic isn't it?

**Comment by Noble-Mushtak** [comment]
What entry previews are you talking about? In my version of the repo, interacting with the entry and seeing the code doesn't work yet because you're still working on it, but the preview image in the entries list works fine on both Chrome and Firefox.

**Comment by bytorbrynden** [comment]
Oh! I need to push my change(s). One second.

**Edit**: Pushed the changes. The program previews I'm referring to, are the ones that get shown after selecting an entry.

**Comment by Noble-Mushtak** [comment]
NOTE: Only a bug on Firefox+Windows (and maybe Firefox+Macs), works on Firefox+Ubuntu.

**Comment by MrMagma** [comment]
Very odd.

**Comment by Noble-Mushtak** [comment]
There's more discussion on this at KA's repo: https://github.com/Khan/live-editor/issues/362

**Comment by Noble-Mushtak** [comment]
@Gigabyte-Giant I think we should close this issue since it's not an issue that we can solve and it's taking up visual space among the GitHub Issues this repo has.

**Comment by bytorbrynden** [comment]
Will do. This is in Khan Academy's hands now.
