### ISSUE TITLE
Syncing erases previous entries score data.

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#22]
**Possible Fix**:
I'll need to reimplement the old(er) syncing method; loop through all the data on Khan Academy, as well as all the data on Firebase, to see what has been added/deleted since last sync.

**Comment by Noble-Mushtak** [comment]
The way to fix this is very easy. All we need to do is store the entries in its own `entries/CONTESTID` child instead of putting the `CONTESTID/entries` inside the `contests` child like we are doing right now. We need to maintain contest data and entry data to contests separately.

**Comment by bytorbrynden** [comment]
I thought of that, but I don't really want to do that. Doing that will require more callbacks when we want to retrieve data. All I'm going to do, is basic `diff` checking.

**Comment by Noble-Mushtak** [comment]
Ah...I didn't think of that. That makes more sense.

**Comment by bytorbrynden** [comment]
Here's how I'm going to do it: https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/b97a3d4ff5ac25362ff77843b81a1b857741362b

I still need to implement the add/remove stuff for entries, but that won't be that hard. Hopefully there are enough comments so you understand each of the conditions.

**Comment by bytorbrynden** [comment]
...just thought of something; should I actually delete stuff? Or should I just mark them as archived?

**Comment by Noble-Mushtak** [comment]
No, we should delete it. If KA deletes a contest/someone else deletes their entry, then we probably should, too.

**Comment by bytorbrynden** [comment]
That's what I was thinking, but what about those odd times when `sync` runs, but the KA API doesn't give us any data? All entries will lose their current score...

**Comment by Noble-Mushtak** [comment]
Make sure the KA API returned data before adding or deleting anything. If it doesn't return data, then don't do anything to Firebase.

**Comment by bytorbrynden** [comment]
Good idea. The only thing is; how do we make sure the KA API returned _everything_ that we need?

**Comment by bytorbrynden** [comment]
Fixed in many commits, however the final commit relating to this bug is https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/5400e952c6bdebf2848a8df54cab95c7a20a5ba1.
