### ISSUE TITLE
Make our Firebase Database Secure

### ISSUE THREAD

**Issue by Noble-Mushtak** [Team-Delta-KA/KA-Contest-Judging-System#28]
I don't know how we're going to do this, but I know that @Gigabyte-Giant does. However, it's still an important issue to remember.

One way we could do this by making Gigabyte Giant's domain the only one allowed to modify the database instead of allowing `localhost` [(instructions on how to do this here)](https://www.firebase.com/docs/web/guide/user-auth.html#section-configuring), meaning that all of our local versions would not be able to test out judging or syncing. This makes it so no one can run the app on `localhost` and delete everything.

I'm not sure if not being able to judge or sync locally is going to be a problem, but I think in any case, we should allow all domains read access because that's not a security issue. It's not like we're storing passwords in Firebase.

**Comment by codeHusky** [comment]
Right now, only authorized google users can really do stuff.
It's pretty darn secure if you ask me.

**Comment by bytorbrynden** [comment]
Yep. I've read the docs. I'll do this eventually.

**Comment by MrMagma** [comment]
Hm... That would put a bit of a kink in testing efforts by other team members though. Maybe have a list of authorized Google users who are judges and are only allowed to write scores, and another list of "developers" who are allowed all they need (not free reign though)

**Comment by Noble-Mushtak** [comment]
@MikaalSky  No, only authorized Google users can judge using the interface we have. Anyone could easily use their JavaScript console and erase the whole Firebase database (although I haven't tested this because if I did, then I would have erased the whole Firebase database).

@Gigabyte-Giant Cool! I just wanted to make this an issue so everyone knew about it.

**Comment by Noble-Mushtak** [comment]
@JavascriptFTW That's also another great idea! I support using user authentication like that.

**Comment by bytorbrynden** [comment]
I'll implement some sort of "role-based" authentication shortly.

**Comment by Noble-Mushtak** [comment]
[You said to break things](https://trello.com/c/Pm8BDOQI/32-try-and-break-things), so I did:

```
var firebaseRef = new Firebase("https://contest-judging-sys.firebaseio.com/");
var contestsRef = firebaseRef.child("contests");
contestsRef.set({"hacker": "Noble Mushtak", "explanation": "https://trello.com/c/Pm8BDOQI/32-try-and-break-things"})
```

I fixed it by clicking "Sync Data". However, to allow "Sync Data" to work, we need the user to have write access to `/contests` without restraint because `Contest_Judging_System.sync()` basically re-writes the child (except for the entries), so I don't know how we'll fix this other than not allowing the "Sync Data" button and instead doing it manually ourselves somehow.

**Comment by Noble-Mushtak** [comment]
Also, anyone can easily judge an entry by just putting `authenticated = true;` into their JavaScript console and then judging as normal.

**Comment by Noble-Mushtak** [comment]
I tried erasing `/allowedJudges/[child]` on Firebase, but it looks like you have security for that pretty good.

**Comment by Noble-Mushtak** [comment]
UPDATE:
We've almost finished Firebase authentication. All we need to do now is any authentication for the "New Contest" interface and authenticate the KACJS-Angus bot.

**Comment by bytorbrynden** [comment]
The authentication for the "New Contest" interface is done, and I just finished the authentication for the KACJS-Angus bot. Closing this.
