### ISSUE TITLE
Program previews don't load in Safari on iOS

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#31]
_Tested using the iOS Simulator_

As the title says; program previews don't load on iOS.

**Comment by bytorbrynden** [comment]
Actually, scratch that; there's a Khan Academy bug that prevents programs that require a larger canvas size, from showing.

**Comment by Noble-Mushtak** [comment]
Khan Academy Computer Science in general doesn't really work for me on my iPad, so I don't think we can do it on our app.
