### ISSUE TITLE
contest.html logs a bunch of Firebase errors

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#32]
...we need to try and figure out where these errors are originating, and try and get rid of them.

**Comment by IdrissDimson** [comment]
those logs aren't always a bad thing but i'll look at it

**Comment by bytorbrynden** [comment]
These ones are. They're actual Firebase.js errors.

**Comment by IdrissDimson** [comment]
I look at em and see what they are

**Comment by bytorbrynden** [comment]
I already know what they are, I just need to decide **how** I want to fix them.
