### ISSUE TITLE
Pamela's feedback

### ISSUE THREAD

**Issue by pamelafox** [Team-Delta-KA/KA-Contest-Judging-System#35]
This is fantastic! Here's my running feedback as I use it:
- I wasn't in the allowed judges list. :-( [Awesome that the feature exists, though!]
- I'd like to default to seeing the code.
- Maybe add an "Unknown" for Level? 
- Can there be different criteria for each contest? Like for Emoji, I need to be able to rate their use of functions. For Organ-ic code, we needed to judge also based on scientific accuracy.
- Can you show # of lines of code next to the tiel? I don't judge entirely based on that, of course, but it's a useful metric to figure out how much work someone put into something.
- How about a slider instead of 1-5? I prefer using a slider for things like this, I get less decision paralysis. E.g. http://imagine-it.org/svg/sliderplugin.html
- What do you think about hiding other people's scores? I think there's a tendency to score based on what other people scored, it biases people. I was kind of thinking that only I (the contest administrator) would see the final scores. I don't want people feeling bad about having super low scores. :-(

**Comment by bytorbrynden** [comment]
Hello Pamela!
 • I'll give you a script to run that'll add you to the allowed judges list.
 • Consider it done! (https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/26f9c2e19d57d757569881e3b5a42e96a13c3876)
 • ~~Sure thing! I'll add that shortly.~~ Added (I'll change the default level to unknown shortly)!
 • In our Trello board, I posted a card for an idea of allowing administrators (IE. you), to create different rubrics. [Trello link](https://trello.com/c/5fLt27I2/27-an-interface-that-allows-administrators-to-create-new-rubrics)
 • ~~I'll definitely look into doing this (shouldn't be hard, just look at the student's code, and increment `linesOfCode` every time we see `\n`)~~. **Edit**: This is done! https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/1b62ffbee3f3c8deb523f5123f056ebad68afad5
 • ~~Sure; I'll implement sliders shortly~~. **Edit**: This is done! https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/c43d20af7e4e10e5ec34c71645887b6666a94bf2
 • We can definitely do that. Before that however, I'll need to finish implementing role-based-authentication.

We appreciate your feedback!! If you have any other ideas, don't hesitate to post them here on GitHub, or email me!

Also, the leaderboard is coming soon (as soon as I finish writing it); I didn't forget about it!

~ Gigabyte Giant

**Comment by bytorbrynden** [comment]
Also, it's worth noting, the allowed judges list goes based on Google UIDs, so we have to add your Google UID to the allowed judges list before you can actually judge entries.
The reason we do this, is so we can prevent random people from logging in and judging, and also so you can't judge more than once!

**Comment by pamelafox** [comment]
Exciting to see so much progress! :)

**Comment by Noble-Mushtak** [comment]
Update on fixing these issues:

> I wasn't in the allowed judges list. :-( [Awesome that the feature exists, though!]

You're still not in the allowed judges list. You might have been before when @Gigabyte-Giant gave you that script, but we've changed how judge authentication works since then. However, if you go [http://gigabytegiant.com/kacjs/Client/](here), I think it should log you into our database and we can easily identify you by your Google display name "Pamela Fox".

> I'd like to default to seeing the code.

Done!

> Maybe add an "Unknown" for Level?

Done!

> Can there be different criteria for each contest? Like for Emoji, I need to be able to rate their use of functions. For Organ-ic code, we needed to judge also based on scientific accuracy.

We're still working on this, but we'll be done soon.

> Can you show # of lines of code next to the tiel? I don't judge entirely based on that, of course, but it's a useful metric to figure out how much work someone put into something.

Done!

> How about a slider instead of 1-5? I prefer using a slider for things like this, I get less decision paralysis. E.g. http://imagine-it.org/svg/sliderplugin.html

Done!

> What do you think about hiding other people's scores? I think there's a tendency to score based on what other people scored, it biases people. I was kind of thinking that only I (the contest administrator) would see the final scores. I don't want people feeling bad about having super low scores. :-(

Done! Only admins like me, @Lokio27, and @Gigabyte-Giant can see scores. However, you're not an admin yet, so you have to follow the instructions at the top so we can make you an admin.

**Comment by Noble-Mushtak** [comment]
We've finished everything on this list. @pamelafox, if you have more feedback or ideas, please make another list for us so we can complete it. Thanks!
