### ISSUE TITLE
"Create Contest" interface?

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#36]
...if we had a simple interface to allow administrators to create new contests, we could allow them to specify more specific criteria for **that** specific contest, to go along with all the general criteria (Code cleanliness, Creativity, etc.).

The only thing with something like this, is I'll have to rethink the way I have Firebase laid out (which is not a problem, it'll just take a bit more time).

Any opinions on this idea would be greatly appreciated!

**Comment by Noble-Mushtak** [comment]
I think they should create the contest program on KA and then submit that program as a contest through some interface. Only allowed judges should be able to do this, too, so we should implement this after we have role-based authentication down.

**Comment by bytorbrynden** [comment]
Either way, Pamela will have to create the contest program on KA, because we'll need the ID...

Before doing this, let's see if @pamelafox has any ideas about this.

**Comment by pamelafox** [comment]
Mmm. I think in an ideal world, anyone would be able to create a contest, and they could set the rubric and settings for whose allowed to judge (anybody, or a list of email addresses, or anybody-that-they-give-a-judging-link to, etc).
Creating the program on Khan Academy first makes sense to me.

**Comment by MrMagma** [comment]
Making it so that judges have to/can manually enter new contests would be an interesting thing to do. It would also eliminate the problem that the system is allowing judging on contests that are already over. Letting humans handle adding the contests would be nice since we could get extra information such as a cutoff date on judging, a date that entries could not be judged before, custom rubrics, and lots of other cool stuff.

**Comment by bytorbrynden** [comment]
@pamelafox I agree. That's something I'd like to shoot for in the future, but I don't think that's an option in v1.0 right now.

**Comment by bytorbrynden** [comment]
I'm going to began implementing something like this. The more I think about it, the better the idea sounds.

Any ideas for features in/on this interface, can be placed as comments on [this Trello card](https://trello.com/c/ikoVoB5D/36-admin-interface).

**Comment by bytorbrynden** [comment]
@Noble-Mushtak has been working on this, and has been doing a great job at it, so I'm going to assign this task to him.

Screenshot of what he has so far:
![monosnap 2015-08-06 15-37-00](https://cloud.githubusercontent.com/assets/4977819/9122833/29dcb656-3c51-11e5-9145-482ea18016ba.png)

**Comment by Noble-Mushtak** [comment]
No problem!

**Comment by bytorbrynden** [comment]
This has been implemented. Going to close this.
