### ISSUE TITLE
Programs Made for Custom Sizes

### ISSUE THREAD

**Issue by Noble-Mushtak** [Team-Delta-KA/KA-Contest-Judging-System#39]
I was randomly testing out our app and found [this entry](http://localhost:8000/Client/entry.html?contest=4802521609666560&entry=5488271774842880). (The domain of that link is `http://localhost:8000`, so make sure you're running the app on port `8000` before trying to visit it.)

As you can see, it has the following error from line `135`:

```
Uncaught Please make the canvas bigger by adding ?width=700&height=400 to the end of the url.
```

I think many KA programmers do this now that we have custom canvas sizes, so how will they be judged from our app if they throw an error like this? Will it be necessary to view the entry on KA if this happens? I don't think we're going to be able to detect this kind of thing, especially because of cross-origin policy.

**Comment by MrMagma** [comment]
We could have some kind of slider or input for the canvas width and height that the judges could use to refresh the iframe with the new URL params.

**Comment by codeHusky** [comment]
Just adding url params to the html document would work just as well. ;)

**Comment by Noble-Mushtak** [comment]
Hm...OK. I'm fixing something else right now, so I'll implement that as soon as possible, although it would be much obliged if someone else could do it. Honestly, I can't believe I didn't think myself. Thanks, guys!

**Comment by bytorbrynden** [comment]
With some clever engineering, we _might_ be able to detect this, and take a couple steps to prevent the student-seeded error messages from popping up during judging.

Will try and look at this when I'm back.

**Comment by Noble-Mushtak** [comment]
Ah...After trying to implement the URL params solution, I found it didn't work because the width of the `<iframe>` is default set to `940` in `entry.js` and therefore, the `<iframe>` isn't big enough to include both the code and the program of width `700`. Works fine when I toggle the code, though, so I'll just make the `<iframe>` adjust to height and put a warning about the width being possibly too big.

**Comment by Noble-Mushtak** [comment]
Can you please merge #44 so I can close this issue? I solved this problem 9 days ago, but the fix still hasn't been merged into the `master` branch of this repo.

**Comment by Noble-Mushtak** [comment]
That pull request has been merged, so I can finally close this issue. Yay!
