### ISSUE TITLE
Is "/tests/app.html" truly a test?

### ISSUE THREAD

**Issue by aikaikaik** [Team-Delta-KA/KA-Contest-Judging-System#4]
It seems that, although this file is located inside the folder "tests", it's the main page of the app. If it is, I thought to add some "branding".

**Comment by bytorbrynden** [comment]
That file doesn't exist in this repository, perhaps you meant to ask @noble-mushtak?

**Comment by Noble-Mushtak** [comment]
Yeah, `tests/app.html` is just a test application. We might use some of the code in our real application, but for now, it's just a test.

Also, here's [my repo](https://github.com/Noble-Mushtak/KA-Contest-Judging-System).
