### ISSUE TITLE
contest.html page continues to load entries, even after we've hit the limit that was set by user

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#51]

**Comment by Noble-Mushtak** [comment]
...I don't understand what this means. `contest.html` works fine for me on both your version and my pull request #53 except for entries that have been deleted, but not picked up by the bot. Please add a description.

**Comment by bytorbrynden** [comment]
This appears to be fixed, going to close for now.
