### ISSUE TITLE
clicking on "view 30 random entries" for the Tomorrowland contest doesn't let me log in

### ISSUE THREAD

**Issue by k4b7** [Team-Delta-KA/KA-Contest-Judging-System#56]
It shows the "login with Google" form, but after entering my credentials and accepting permission it brings me back to the login form instead of taking me to the 30 random entries.

**Comment by bytorbrynden** [comment]
Thanks for reporting Kevin! I'll take a look right now.

**Comment by Noble-Mushtak** [comment]
Try clicking another contest for now. We're testing something with the Tomorrowland contest, so it won't be working properly for right now.

**Comment by bytorbrynden** [comment]
Also, sometimes you have to click the "Login with Google" button twice, I'll try and fix that soon.

Also, as mentioned by @Noble-Mushtak, steer clear of the Tomorrowland contest for now, that's what we're using to test something for @pamelafox.

**Comment by k4b7** [comment]
Clicking the login button at the top worked, but trying to login by clicking on any (I just tried the first two) of the contests put me into the afore mentioned login cycle.

**Comment by bytorbrynden** [comment]
Ahah! That's due to the way we changed our authentication yesterday.

We'll look into fixing this. We do apologize about the inconveniences!

**Comment by codeHusky** [comment]
@kevinb7 For the best response time with the issues you're having, please join our Gitter chatroom. (Link to join in the README.md)

**Comment by k4b7** [comment]
Great work!  @pamelafox showed off all of your hard work to everyone at Khan Academy.  It was well received.

**Comment by bytorbrynden** [comment]
We do appreciate all the support we've been receiving. When we first started this project, we had no clue it would get such good feedback!

Thanks again for all the support! We really appreciate it. :)

**Comment by bytorbrynden** [comment]
This should be fixed now @kevinb7. To fix it, all I did was revert back to using OAuth popups, instead of redirects.

Please try http://gigabytegiant.com/kacjs/Client/contest.html?contest=4688911017312256&entries=30 again. Please note, your browser's popup blocker is going to block the OAuth popup, as it wasn't triggered by a user event.

I'll implement @Noble-Mushtak's more solid change, tomorrow.

**Comment by Noble-Mushtak** [comment]
OK, @Gigabyte-Giant has implemented my solid change, so I believe that this issue has been fixed without needing automatic popups. Can you please [test this again](http://gigabytegiant.com/kacjs/Client/contest.html?contest=4688911017312256&entries=30) and make sure nothing weird happens? Please make sure you visit the Web site with a disabled cache. If this issue still persists, please [go to Gitter](https://gitter.im/Team-Delta-KA/KA-Contest-Judging-System) so you can tell us more about it. Thanks!

**Comment by bytorbrynden** [comment]
I'm pretty much certain that this specific issue has been fixed, so I'm going to close this. If you have any more problems with this @kevinb7, please do reopen this, and take to Gitter.
