### ISSUE TITLE
"Login with Google" button has to be clicked twice for authentication to be recognized by app

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#57]
I thought we already fixed this, but, evidently, we didn't.

**Comment by Noble-Mushtak** [comment]
This does not happen for me because we fixed it (in fact, I think you fixed it).

**Comment by bytorbrynden** [comment]
For me, it requires two clicks for any of the button toggling (hiding of login button, showing of logout button, etc) to take place.

**Comment by bytorbrynden** [comment]
Actually, scratch that. It just took `auth.firebase` a while to load and perform the redirect. Closing.
