### ISSUE TITLE
Entry Count doesn't match Khan Academy spinoff count

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#59]
...I don't know if this is a Khan Academy thing, or if the bot isn't updating the entry count.

Compare the following contest's spinoff count, to the entry count that we have.

Spinoff count on Khan Academy: http://take.ms/7lAh9
Entry count in KACJS: http://take.ms/BWG5Z

I think this is because of spinoffs that fall under the `spin-offs that didn't change any code, are by child accounts, or are by anonymous users` criteria, enforced by Khan Academy.

Entries that aren't shown on Khan Academy, are **not** picked up by KACJS-Angus, however, I didn't think the spinoff count on Khan Academy, is/was updated for spinoffs that fall under the above criteria.

/cc @pamelafox & @kevinb7

**Comment by codeHusky** [comment]
I think you're right because of the anti-spam.
?sort=3/4 might be a good option to enable showing the hidden ones.

**Comment by bytorbrynden** [comment]
No, I don't want to show hidden ones, I just want to make sure my assumptions are correct.

**Comment by bytorbrynden** [comment]
After a bit more investigation, I've verified that my assumptions were/are correct. Am closing this for now.
