### ISSUE TITLE
Suggestion: only provide a link to the KA page after judging

### ISSUE THREAD

**Issue by k4b7** [Team-Delta-KA/KA-Contest-Judging-System#61]

**Comment by codeHusky** [comment]
Which page is this affected by?

**Comment by k4b7** [comment]
When you're judging one of the entries there's a button you can click on to view the entry on KA.  Right now it pops up a dialog with a warning before allowing you to view the entry on KA.  I thought it might be better to only provide the link after judging and just not have the dialog.

**Comment by Noble-Mushtak** [comment]
I think @Gigabyte-Giant wanted people to have the option to view the entry on KA while judging in case they wanted to see more info about the entry. However, he'll give you a better answer when he comes back tomorrow morning.

**Comment by Noble-Mushtak** [comment]
Oh, wait, I remember why @Gigabyte-Giant added that button now! It was because viewing entries on Firefox+Windows doesn't work: https://github.com/Team-Delta-KA/KA-Contest-Judging-System/issues/14

**Comment by Noble-Mushtak** [comment]
Therefore, we need this button in order for people to judge entries from Firefox+Windows computers.

**Comment by codeHusky** [comment]
Oh yeah. I'll close this issue for now until that gets fixed.

**Comment by bytorbrynden** [comment]
No need to close this, if @kevinb7 wants this, I'll figure out a way to do something like this.

**Comment by bytorbrynden** [comment]
@kevinb7 In https://github.com/Team-Delta-KA/KA-Contest-Judging-System/commit/0fdce35c13f3ffa29c995fc50fcd14b6549697d2, I commented out the button, so it no longer appears in the UI...

I'm going to wait a while before completely getting rid of the button's code, just in case #14 surfaces again for some reason.

I'll deploy a new copy of KACJS to the production server later on. Feel free to close this whenever.

**Edit**: Version 1.0.2 deployed to http://gigabytegiant.com/kacjs. Please let me know if you have any issues.
