### ISSUE TITLE
Leaderboard fails to load data

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#69]
I'm not sure what is causing this, as it only occurs after my refactoring, which is odd because the only thing that I changed relating to the leaderboard, in my refactoring, was a few comments, and some whitespace...

We **cannot** publish the latest copy of KACJS until this gets fixed.

/cc @JavascriptFTW; Perhaps you could shed some light on this one?

**Comment by MrMagma** [comment]
I'll look into this when I get time this afternoon. Can't really find anything that could be messing up in my brief inspection so far.

**Comment by Noble-Mushtak** [comment]
Someone put in a `setTimeout()` instead of a `setInterval()` in `Backend/contest_judging_sys.js` for some reason. I'm definitely sure I fixed this problem before, so don't know how it happened again, but maybe something weird happened while refactoring? Anyway, pull request coming right up!

**Comment by IdrissDimson** [comment]
nice find noble!

**Comment by Noble-Mushtak** [comment]
Wait...I've made the leaderboard load, but now all of the scores are 0 for some reason.

**Comment by Noble-Mushtak** [comment]
Ah...I see the problem. Someone typed `i < [...]` instead of `roInd < [...]`. Another refactoring problem.

**Comment by bytorbrynden** [comment]
That "someone", had to have been you @Noble-Mushtak. I'm the one who renamed variables such as `i`, to things like `roInd`...

**Comment by Noble-Mushtak** [comment]
Oh...Sorry!
