### ISSUE TITLE
Content Positioning is Messed up on Mobile Size Screens

### ISSUE THREAD

**Issue by MrMagma** [Team-Delta-KA/KA-Contest-Judging-System#75]
The positioning of content is not exactly good on mobile sized screens. The contest controls overlap the description causing it to be partially unreadable.
## Examples

360 by 640 screen (Nokia N9)
![](http://img.prntscr.com/img?url=http://i.imgur.com/OpZBROL.png)

375 by 627 screen (iPhone 6)
![](http://img.prntscr.com/img?url=http://i.imgur.com/Q76lEY6.png)

The smallest device screen size that this problem does not occur on seems to be an iPad mini (768 by 1024). On large enough devices this problem does not occur when in Landscape mode indicating that the cause is simple lack of adaptivity to different screen widths on the part of the Materialize framework.

**Comment by bytorbrynden** [comment]
I'm not expert on mobile-first design (or design in general), so I think our @sparkstudios/designers should take a look at this.

**Comment by bytorbrynden** [comment]
I believe https://github.com/sparkstudios/Contest-Judging-System-for-KA/commit/7e7b8796ad983aa18257656a25ada9d9f3e38f5b fixes this.

The following screenshot shows how we're showing the "contest page" on a mobile device in the portrait orientation.
![cjska_mobile1](https://cloud.githubusercontent.com/assets/4977819/10762667/f8927638-7c94-11e5-8516-34b222f5bef1.png)

If you have any more problems with this @JavascriptFTW, please feel free to reopen this issue.

Thanks!
