### ISSUE TITLE
`Contest_Judging_System.getStoredContests()` does not work

### ISSUE THREAD

**Issue by aikaikaik** [Team-Delta-KA/KA-Contest-Judging-System#9]
I tried to run the `\Client\index.html` and it did not load, `KA_API.js` did work on the javascript console, when I tried to run this: `Contest_Judging_System.getStoredContests(function(a){console.log(a);});` there was no result.

**Comment by bytorbrynden** [comment]
This is because I'm in the process of changing permissions on Firebase.
