### ISSUE TITLE
Ctrl/Cmd Clicking entries doesn't open them in a new tab

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#95]
Originally mentioned by @pamelafox.

Steps to reproduce:
- Navigate to `localhost:3000`
- Click the "View Entries" button for any contest
- Attempt to Ctrl/Cmd command click on an entry

Expected behavior: The entry should be opened in a new browser tab.
Experienced behavior: The entry opens in the current tab.

**Comment by MrMagma** [comment]
This was caused by me. I didn't wrap the entries in an `a` tag and just attached a custom click listener. I did not think of this when I did that.
See [contest.js](https://github.com/sparkstudios/Contest-Judging-System-for-KA/blob/master/src/client/contest.js#L31-L33)

**Comment by bytorbrynden** [comment]
Yeah, I knew it was you as soon as it was reported.

It's an easy fix. I'll push out the fix in my next push.

**Comment by bytorbrynden** [comment]
Squashed by https://github.com/sparkstudios/Contest-Judging-System-for-KA/commit/d246cb87e3e4805d6dc2acf660f82c238eb3f175.
